(() => {
  "use strict";
  const ADMIN_UID = "70WNrO5zubWwSxegfpSPRkCIfhw1";
  const state = { lang: localStorage.getItem("mindcare_language") || "ar", db: null, firebaseReady: false, customTopics: {} };
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => [...r.querySelectorAll(s)];
  const esc = v => String(v ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));

  const sources = {
    anxiety: "https://www.nimh.nih.gov/health/topics/anxiety-disorders",
    depression: "https://www.who.int/news-room/fact-sheets/detail/depression",
    panic: "https://www.nimh.nih.gov/health/publications/panic-disorder-when-fear-overwhelms",
    ocd: "https://www.nimh.nih.gov/health/publications/obsessive-compulsive-disorder-when-unwanted-thoughts-and-repetitive-behaviors-take-over",
    trauma: "https://www.nimh.nih.gov/health/publications/post-traumatic-stress-disorder-ptsd",
    sleep: "https://www.nhlbi.nih.gov/health/sleep-deprivation",
    addiction: "https://nida.nih.gov/publications/drugs-brains-behavior-science-addiction",
    "self-esteem": "https://www.nimh.nih.gov/health/publications/psychotherapies",
    relationships: "https://www.nimh.nih.gov/health/publications/psychotherapies",
    family: "https://www.nimh.nih.gov/health/publications/psychotherapies",
    communication: "https://www.nimh.nih.gov/health/publications/psychotherapies"
  };
  const topics = {
    anxiety:{icon:"fa-cloud",ar:{title:"القلق",intro:"القلق قد يظهر كخوف أو قلق زائد يصعب التحكم فيه، وقد يؤثر في الدراسة أو العمل أو العلاقات عندما يصبح مستمرًا أو شديدًا.",symptoms:["قلق أو خوف متكرر","صعوبة في التحكم في القلق","توتر أو تهيج","صعوبة في التركيز أو النوم","تجنب مواقف بسبب الخوف"],seek:"إذا استمر القلق أو بدأ يؤثر بوضوح في حياتك اليومية، فقد يكون من المفيد التحدث إلى مختص."},en:{title:"Anxiety",intro:"Anxiety can involve excessive fear or worry that becomes difficult to control and may interfere with everyday life.",symptoms:["Repeated worry or fear","Difficulty controlling worry","Tension or irritability","Problems with concentration or sleep","Avoiding situations because of fear"],seek:"If anxiety persists or clearly interferes with daily life, talking with a qualified professional may be useful."}},
    depression:{icon:"fa-cloud-sun",ar:{title:"الاكتئاب",intro:"الاكتئاب قد يتضمن مزاجًا منخفضًا أو فقدان الاهتمام لفترة ممتدة، مع تغيرات في الطاقة والنوم والتركيز وغيرها.",symptoms:["حزن أو انخفاض مزاج مستمر","فقدان الاهتمام أو المتعة","تعب أو انخفاض الطاقة","صعوبة في التركيز","تغيرات في النوم أو الشهية","مشاعر يأس أو انخفاض تقدير الذات"],seek:"إذا استمرت هذه الأعراض أو أثرت في حياتك، من المهم طلب تقييم من مختص. وإذا وُجد خطر فوري أو أفكار بإيذاء النفس، اطلب مساعدة طارئة محلية فورًا."},en:{title:"Depression",intro:"Depression can involve persistent low mood or loss of interest, together with changes in energy, sleep, concentration, and more.",symptoms:["Persistent low mood","Loss of interest or pleasure","Low energy or fatigue","Difficulty concentrating","Changes in sleep or appetite","Hopelessness or low self-worth"],seek:"If symptoms persist or interfere with life, professional assessment can help. If there is immediate danger or thoughts of self-harm, seek local emergency help immediately."}},
    panic:{icon:"fa-wind",ar:{title:"نوبات الهلع",intro:"نوبة الهلع هي موجة مفاجئة من الخوف أو الانزعاج الشديد قد يصاحبها تسارع القلب أو ضيق التنفس أو الدوخة. وجود نوبة واحدة لا يعني بالضرورة اضطراب الهلع.",symptoms:["خوف شديد مفاجئ","تسارع ضربات القلب","تعرق أو ارتجاف","ضيق تنفس أو إحساس بالاختناق","دوخة أو تنميل","خوف مستمر من تكرار النوبة"],seek:"إذا تكررت النوبات أو أدت إلى تجنب أماكن أو أنشطة، تحدث مع مختص. الأعراض الجسدية الشديدة أو غير المعتادة تستحق أيضًا تقييمًا طبيًا مناسبًا."},en:{title:"Panic attacks",intro:"A panic attack is a sudden wave of intense fear or discomfort that can include racing heart, breathing difficulty, dizziness, and other physical symptoms. One attack does not necessarily mean panic disorder.",symptoms:["Sudden intense fear","Racing heart","Sweating or trembling","Breathing difficulty","Dizziness or tingling","Ongoing fear of another attack"],seek:"If attacks recur or lead to avoidance, talk with a qualified professional. Severe or unusual physical symptoms also deserve appropriate medical evaluation."}},
    ocd:{icon:"fa-rotate",ar:{title:"الوسواس القهري",intro:"قد يتضمن الوسواس القهري أفكارًا متكررة ومُلِحّة (وساوس) وسلوكيات أو أفعالًا عقلية متكررة (أفعال قهرية) تسبب ضيقًا أو تعطل الحياة اليومية.",symptoms:["أفكار أو صور ذهنية متطفلة وغير مرغوبة","حاجة متكررة للتأكد أو التنظيف أو الترتيب","أفعال قهرية لتخفيف القلق","استهلاك وقت كبير في هذه الأفكار أو السلوكيات","تجنب مواقف تثير الوساوس"],seek:"إذا كانت الأفكار أو السلوكيات تستهلك وقتًا أو تسبب ضيقًا أو تعطل حياتك، تحدث مع مختص. لا تحاول تشخيص نفسك من قائمة الأعراض وحدها."},en:{title:"OCD",intro:"OCD can involve recurring intrusive thoughts and repetitive behaviors or mental acts that cause distress or interfere with daily life.",symptoms:["Intrusive unwanted thoughts or images","Repeated checking, cleaning, or ordering","Compulsions used to reduce anxiety","Significant time spent on symptoms","Avoidance of triggers"],seek:"If symptoms take substantial time, cause distress, or interfere with life, speak with a qualified professional. A symptom list alone cannot diagnose OCD."}},
    trauma:{icon:"fa-feather",ar:{title:"آثار الصدمات",intro:"بعد تجربة صعبة أو مهددة قد تظهر استجابات مثل الخوف أو الحزن أو صعوبة النوم والتركيز. كثير من الناس يتحسنون مع الوقت، لكن استمرار الأعراض أو تأثيرها في الحياة يستحق الانتباه.",symptoms:["ذكريات أو أحلام مزعجة","تجنب ما يذكّر بالتجربة","التوتر أو فرط اليقظة","صعوبة النوم أو التركيز","مشاعر خوف أو غضب أو ذنب","الابتعاد عن الآخرين"],seek:"إذا استمرت الأعراض وأصبحت تعطل العلاقات أو العمل أو الدراسة، يمكن لمختص تقييمها وتقديم الدعم المناسب."},en:{title:"Trauma",intro:"After a difficult or threatening event, people may experience fear, sadness, sleep problems, or concentration difficulties. Many recover over time, while persistent or disruptive symptoms deserve attention.",symptoms:["Distressing memories or dreams","Avoiding reminders","Feeling tense or on guard","Sleep or concentration problems","Fear, anger, guilt, or shame","Feeling socially detached"],seek:"If symptoms persist and interfere with relationships, work, or school, a qualified professional can assess them and provide support."}},
    sleep:{icon:"fa-moon",ar:{title:"النوم",intro:"اضطراب النوم أو نقصه قد يؤثر في المزاج والانتباه والذاكرة والطاقة والقدرة على التعامل مع المشاعر.",symptoms:["صعوبة في النوم أو الاستمرار فيه","الاستيقاظ دون شعور بالراحة","النعاس أو التعب خلال النهار","ضعف التركيز","تغير المزاج أو سرعة الانفعال"],seek:"إذا كانت مشاكل النوم مستمرة أو تؤثر في يومك، تحدث مع طبيب أو مختص مناسب لمعرفة الأسباب والخطوات التالية."},en:{title:"Sleep",intro:"Poor or insufficient sleep can affect mood, attention, memory, energy, and emotional regulation.",symptoms:["Difficulty falling or staying asleep","Waking without feeling rested","Daytime sleepiness or fatigue","Reduced concentration","Mood changes or irritability"],seek:"If sleep problems persist or affect your day, talk with an appropriate healthcare professional to explore causes and next steps."}},
    addiction:{icon:"fa-hands-holding-circle",ar:{title:"الإدمان واستخدام المواد",intro:"الاستخدام القهري للمواد قد يستمر رغم العواقب السلبية، وقد يصاحبه تغير في السلوك أو العلاقات أو الدراسة والعمل. المصطلحات والتشخيصات الدقيقة تحتاج إلى تقييم مهني.",symptoms:["صعوبة تقليل أو إيقاف الاستخدام","الاستمرار رغم أضرار واضحة","انشغال متزايد بالحصول على المادة أو استخدامها","إهمال مسؤوليات أو أنشطة مهمة","مشكلات في العلاقات أو العمل/الدراسة","استخدام المادة للتعامل مع المشاعر بشكل متكرر"],seek:"عند وجود فقدان للسيطرة أو أضرار مستمرة، طلب المساعدة المتخصصة خطوة مهمة. حالات التسمم أو الانسحاب الخطير تحتاج إلى رعاية طبية عاجلة."},en:{title:"Addiction and substance use",intro:"Compulsive substance use may continue despite harmful consequences and can affect behavior, relationships, work, or study. Exact diagnosis requires professional assessment.",symptoms:["Difficulty cutting down or stopping","Continuing despite clear harm","Increasing preoccupation with use","Neglecting responsibilities","Problems in relationships or work/school","Repeatedly using substances to cope with emotions"],seek:"When control is lost or harms continue, professional support can be important. Severe intoxication or dangerous withdrawal requires urgent medical care."}},
    "self-esteem":{icon:"fa-seedling",ar:{title:"تقدير الذات",intro:"تقدير الذات يتعلق بالطريقة التي ننظر بها إلى قيمتنا وقدراتنا. قد يتأثر بالنقد المستمر أو المقارنات أو التجارب الصعبة.",symptoms:["انتقاد ذاتي قاسٍ","مقارنة مستمرة بالآخرين","صعوبة تقبل الأخطاء","الخوف المبالغ من الرفض","صعوبة وضع حدود صحية"],seek:"إذا أصبحت الأفكار السلبية عن نفسك تؤثر في علاقاتك أو قراراتك أو مزاجك، يمكن أن يساعدك التحدث مع مختص."},en:{title:"Self-esteem",intro:"Self-esteem concerns how we view our worth and abilities and can be affected by criticism, comparisons, or difficult experiences.",symptoms:["Harsh self-criticism","Frequent comparison with others","Difficulty accepting mistakes","Strong fear of rejection","Difficulty setting healthy boundaries"],seek:"If negative self-beliefs affect relationships, decisions, or mood, speaking with a professional may help."}},
    relationships:{icon:"fa-people-arrows",ar:{title:"العلاقات",intro:"العلاقات الصحية تحتاج إلى وضوح في الاحتياجات والحدود، واحترام متبادل، وقدرة على التعبير والاستماع.",symptoms:["تكرار سوء الفهم","صعوبة التعبير عن الاحتياجات","حدود غير واضحة","خوف من الخلاف","أنماط متكررة من التوتر"],seek:"إذا أصبح الصراع متكررًا أو مؤذيًا أو يصعب التعامل معه بمفردك، قد يكون الدعم المهني مفيدًا."},en:{title:"Relationships",intro:"Healthy relationships involve clear needs and boundaries, mutual respect, and the ability to communicate and listen.",symptoms:["Repeated misunderstandings","Difficulty expressing needs","Unclear boundaries","Fear of conflict","Recurring patterns of tension"],seek:"If conflict becomes persistent, harmful, or difficult to manage alone, professional support may be useful."}},
    family:{icon:"fa-house-user",ar:{title:"الأسرة",intro:"الأسرة قد تكون مصدر دعم، وقد تكون أيضًا مساحة تظهر فيها الخلافات والضغوط. فهم أنماط التفاعل يساعد على اختيار طرق تواصل أكثر وضوحًا.",symptoms:["خلافات متكررة","صعوبة الاستماع المتبادل","توقعات غير واضحة","تدخل في الحدود الشخصية","تراكم مشاعر دون نقاش"],seek:"إذا كانت الخلافات تؤثر بشدة في الأمان أو العلاقات أو الحياة اليومية، تحدث مع مختص مناسب."},en:{title:"Family",intro:"Family can be a source of support and also a place where conflict and stress appear. Understanding interaction patterns can support clearer communication.",symptoms:["Recurring conflict","Difficulty listening to one another","Unclear expectations","Boundary difficulties","Feelings building up without discussion"],seek:"If conflict strongly affects safety, relationships, or daily life, consider speaking with an appropriate professional."}},
    communication:{icon:"fa-comments",ar:{title:"التواصل",intro:"التواصل الواضح لا يعني الاتفاق دائمًا؛ بل يعني القدرة على التعبير عن الاحتياجات والاستماع ووضع حدود محترمة.",symptoms:["التعبير بطريقة هجومية أو دفاعية","صعوبة قول لا","سوء فهم متكرر","الانسحاب بدل الحوار","صعوبة طلب الدعم"],seek:"إذا أصبحت أنماط التواصل سببًا مستمرًا للضغط أو النزاع، قد تساعدك الاستشارة المهنية على فهمها وتغييرها."},en:{title:"Communication",intro:"Clear communication does not require constant agreement. It involves expressing needs, listening, and setting respectful boundaries.",symptoms:["Aggressive or defensive expression","Difficulty saying no","Repeated misunderstandings","Withdrawing instead of discussing","Difficulty asking for support"],seek:"If communication patterns are a continuing source of stress or conflict, professional guidance may help."}}
  };
  const providers={tasbeh:{name:"Tasbeh Mohamed",specialty:{ar:"دعم نفسي ونمو شخصي وعلاقات",en:"Personal support, growth, and relationships"},bio:{ar:"تقدم Tasbeh مساحة هادئة للحوار وفهم المشاعر والعلاقات والنمو الشخصي، مع التركيز على خطوات عملية تناسب احتياجات الشخص.",en:"Tasbeh offers a calm space to explore emotions, relationships, and personal growth, with attention to practical steps that fit the person's needs."}},mariam:{name:"Mariam Mahmoud",specialty:{ar:"الصحة النفسية وتطوير الذات والعلاقات",en:"Mental wellness, self-development, and relationships"},bio:{ar:"تركز Mariam على دعم فهم الذات والتعامل مع الضغوط والعلاقات وبناء عادات أكثر توازنًا في الحياة اليومية.",en:"Mariam focuses on self-understanding, coping with stress and relationships, and building more balanced everyday habits."}}};

  function t(ar,en){return state.lang==="ar"?ar:en}
  function applyLanguage(){document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==="ar"?"rtl":"ltr";document.body.classList.toggle("english",state.lang==="en");$("#languageSwitch").textContent=state.lang==="ar"?"EN":"AR";$$('[data-ar][data-en]').forEach(el=>{if(el.matches("input,textarea")){el.placeholder=state.lang==="ar"?el.dataset.ar||el.placeholder:el.dataset.en||el.placeholder}else if(!el.querySelector("i")||el.children.length===0){el.textContent=state.lang==="ar"?el.dataset.ar:el.dataset.en}else{const icon=el.querySelector("i");el.textContent=state.lang==="ar"?el.dataset.ar:el.dataset.en;if(icon)el.append(" ",icon)}});document.title=state.lang==="ar"?"MindCare | الصحة النفسية":"MindCare | Mental Wellness";updateDynamicPlaceholders();}
  function updateDynamicPlaceholders(){const n=$("#bookingName"),p=$("#bookingPhone"),m=$("#bookingMessage");if(n)n.placeholder=t("اكتب اسمك","Enter your name");if(p)p.placeholder=t("01xxxxxxxxx","01xxxxxxxxx");if(m)m.placeholder=t("اكتب أي ملاحظة تريد مشاركتها...","Write an optional note...")}
  function openModal(id){const el=$(id);if(!el)return;el.classList.add("open");document.body.classList.add("modal-open")}
  function closeModals(){ $$(".modal.open").forEach(m=>m.classList.remove("open"));document.body.classList.remove("modal-open") }
  function renderTopic(key){const built=topics[key];const custom=state.customTopics[key];const data=built||custom;if(!data)return;const d=data[state.lang], icon=data.icon||"fa-circle-info";const srcUrl=built?sources[key]:((custom&&custom.sourceUrl)||"#");$("#topicModalContent").innerHTML=`<div class="topic-modal-content"><div class="topic-meta"><div class="topic-modal-icon"><i class="fa-solid ${icon}"></i></div><div><span class="section-kicker">${esc(t("تثقيف نفسي","Mental health education"))}</span><h2>${esc(d.title)}</h2></div></div><div class="topic-section"><h4>${esc(t("نظرة عامة","Overview"))}</h4><p>${esc(d.intro)}</p></div><div class="topic-section"><h4>${esc(t("علامات وأعراض شائعة","Common signs and symptoms"))}</h4><ul>${d.symptoms.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div><div class="topic-section"><h4>${esc(t("متى تطلب المساعدة؟","When to seek help"))}</h4><p>${esc(d.seek)}</p></div><div class="warning-box">${esc(t("هذه المعلومات للتثقيف فقط ولا تُستخدم لتشخيص نفسك. التشخيص يحتاج إلى تقييم من مختص مؤهل.","This information is educational only and should not be used to diagnose yourself. Diagnosis requires evaluation by a qualified professional."))}</div><div class="topic-section"><a class="source-link" href="${esc(srcUrl)}" target="_blank" rel="noopener noreferrer">${esc(t("المصدر الموثوق","Reliable source"))} <i class="fa-solid fa-arrow-up-right-from-square"></i></a></div></div>`;openModal("#topicModal")}
  function renderProvider(key){const p=providers[key];if(!p)return;$("#providerModalContent").innerHTML=`<div class="provider-profile"><div class="provider-head"><div class="provider-avatar"><i class="fa-solid fa-user"></i></div><div><h2>${esc(p.name)}</h2><p>${esc(p.specialty[state.lang])}</p></div></div><p class="provider-bio">${esc(p.bio[state.lang])}</p><div class="topic-section"><h4>${esc(t("مجالات الدعم","Areas of support"))}</h4><ul><li>${esc(t("الصحة النفسية والنمو الشخصي","Mental wellness and personal growth"))}</li><li>${esc(t("العلاقات والتواصل","Relationships and communication"))}</li><li>${esc(t("التعامل مع الضغوط اليومية","Coping with everyday stress"))}</li></ul></div><button class="btn btn-primary full-width" data-open-booking data-selected-provider="${esc(p.name)}">${esc(t("احجز موعدًا مع هذا المختص","Book with this specialist"))}</button></div>`;openModal("#providerModal")}
  function initFirebase(){try{if(!window.firebase||!window.MINDCARE_FIREBASE_CONFIG)return; if(!firebase.apps.length)firebase.initializeApp(window.MINDCARE_FIREBASE_CONFIG);state.db=firebase.firestore();state.firebaseReady=true}catch(e){console.error("Firebase init failed",e)}}
  async function loadCustomTopics(){if(!state.firebaseReady)return;try{const snap=await state.db.collection("topics").get();const map={};snap.forEach(doc=>{map[doc.id]=doc.data()});state.customTopics=map;renderCustomTopicCards();applyLanguage()}catch(e){console.error("Could not load custom topics",e)}}
  function renderCustomTopicCards(){const grid=$("#customTopicsGrid"),section=$("#moreTopicsSection");if(!grid||!section)return;const keys=Object.keys(state.customTopics);if(!keys.length){section.hidden=true;grid.innerHTML="";return}section.hidden=false;grid.innerHTML=keys.map((key,i)=>{const c=state.customTopics[key];const icon=c.icon||"fa-circle-info";const ar=c.ar||{},en=c.en||{};return `<button class="topic-card" data-topic="${esc(key)}"><span class="topic-number">${String(i+1).padStart(2,"0")}</span><span class="topic-icon"><i class="fa-solid ${icon}"></i></span><h3 data-ar="${esc(ar.title)}" data-en="${esc(en.title)}">${esc(state.lang==="ar"?ar.title:en.title)}</h3><p data-ar="${esc(ar.intro)}" data-en="${esc(en.intro)}">${esc(state.lang==="ar"?ar.intro:en.intro)}</p><span class="card-link" data-ar="اعرف أكثر" data-en="Learn more">${esc(t("اعرف أكثر","Learn more"))} <i class="fa-solid fa-arrow-left"></i></span></button>`}).join("")}
  function resetSlotSelect(msg){const s=$("#bookingSlot");s.innerHTML=`<option value="">${esc(msg)}</option>`;s.disabled=true}
  function formatTime(hm){const [hh,mm]=String(hm).split(":").map(Number);if(Number.isNaN(hh)||Number.isNaN(mm))return hm;const ap=hh>=12?"PM":"AM";const h=hh%12||12;return `${String(h).padStart(2,"0")}:${String(mm).padStart(2,"0")} ${ap}`}
  async function loadSlots(){const provider=$("#bookingProvider").value,date=$("#bookingDate").value;const status=$("#slotStatus");if(!provider||!date){resetSlotSelect(t("اختر المختص والتاريخ أولًا","Choose a specialist and date first"));status.textContent="";return}if(!state.firebaseReady){resetSlotSelect(t("الحجز غير متصل بقاعدة البيانات حاليًا","Booking is not connected to the database"));status.textContent=t("تحقق من إعداد Firebase.","Check Firebase configuration.");status.className="slot-status error";return}resetSlotSelect(t("جاري تحميل المواعيد...","Loading available slots..."));status.textContent="";try{let snap;try{snap=await state.db.collection("slots").where("provider","==",provider).where("date","==",date).where("booked","==",false).get()}catch(firstErr){snap=await state.db.collection("slots").where("provider","==",provider).where("date","==",date).get()}const rows=snap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.booked!==true).sort((a,b)=>String(a.time).localeCompare(String(b.time)));const select=$("#bookingSlot");if(!rows.length){resetSlotSelect(t("لا توجد مواعيد متاحة لهذا اليوم","No available appointments for this date"));status.textContent=t("اختر تاريخًا آخر أو مختصًا آخر.","Try another date or specialist.");return}select.disabled=false;select.innerHTML=`<option value="">${esc(t("اختر الموعد","Choose a time"))}</option>`+rows.map(x=>`<option value="${esc(x.id)}" data-time="${esc(x.time||"")}">${esc(formatTime(x.time||""))}</option>`).join("");status.textContent=t(`${rows.length} موعد متاح`,`${rows.length} slot(s) available`);status.className="slot-status ok"}catch(e){console.error(e);resetSlotSelect(t("تعذر تحميل المواعيد","Could not load appointments"));status.textContent=t("حدث خطأ في الاتصال بقاعدة البيانات.","A database error occurred.");status.className="slot-status error"}}
  function openBooking(provider){const form=$("#bookingForm");form.reset();$("#bookingSuccess").classList.remove("show");$("#bookingSuccess").textContent="";$("#bookingSubmit").disabled=false;$("#bookingDate").min=new Date().toISOString().slice(0,10);resetSlotSelect(t("اختر المختص والتاريخ أولًا","Choose a specialist and date first"));if(provider)$("#bookingProvider").value=provider;openModal("#bookingModal");if(provider&&$("#bookingDate").value)loadSlots()}
  async function submitBooking(e){e.preventDefault();const form=e.currentTarget;const btn=$("#bookingSubmit");const success=$("#bookingSuccess");if(!state.firebaseReady){success.textContent=t("الحجز غير متاح حاليًا لأن Firebase غير متصل.","Booking is currently unavailable because Firebase is not connected.");success.classList.add("show");return}const data=new FormData(form);const slotId=data.get("slot"),provider=data.get("provider"),date=data.get("date");if(!slotId){alert(t("اختر موعدًا متاحًا أولًا.","Please choose an available time first."));return}btn.disabled=true;btn.classList.add("loading");try{const bookingRef=state.db.collection("bookings").doc();const slotRef=state.db.collection("slots").doc(slotId);await state.db.runTransaction(async tx=>{const slotSnap=await tx.get(slotRef);if(!slotSnap.exists)throw new Error("slot-not-found");const slot=slotSnap.data();if(slot.booked===true)throw new Error("slot-booked");if(slot.provider!==provider||slot.date!==date)throw new Error("slot-mismatch");tx.set(bookingRef,{name:data.get("name").trim(),phone:data.get("phone").trim(),message:data.get("message").trim(),providerId:provider.toLowerCase().replace(/\s+/g,"-"),provider,date,time:slot.time,slotId,status:"pending",createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});tx.update(slotRef,{booked:true,bookingId:bookingRef.id,updatedAt:firebase.firestore.FieldValue.serverTimestamp()})});success.textContent=t("تم إرسال طلب الحجز بنجاح. سيتم التعامل معه من خلال نظام الإدارة.","Your booking request was submitted successfully. It will be handled through the admin system.");success.classList.add("show");form.reset();resetSlotSelect(t("اختر المختص والتاريخ أولًا","Choose a specialist and date first"));}catch(err){console.error(err);success.textContent=err.message==="slot-booked"?t("هذا الموعد تم حجزه للتو. اختر موعدًا آخر.","This slot was just booked. Please choose another one."):t("تعذر إرسال الحجز. حاول مرة أخرى.","The booking could not be submitted. Please try again.");success.classList.add("show")}finally{btn.disabled=false;btn.classList.remove("loading")}}
  const questions=["هل شعرت خلال الأسبوعين الماضيين بانخفاض واضح في المزاج أو الاهتمام؟","هل شعرت بقلق أو توتر يصعب التحكم فيه؟","هل أثرت مشاعرك في نومك أو تركيزك؟","هل بدأت تتجنب أشياء أو أماكن بسبب الخوف أو الضغط؟","هل أثرت هذه المشاعر في الدراسة أو العمل أو العلاقات؟"];
  function renderAssessment(){const box=$("#assessmentQuestions");box.innerHTML=questions.map((q,i)=>`<div class="assessment-question"><p>${i+1}. ${esc(state.lang==="ar"?q:["Have you had a clear drop in mood or interest during the past two weeks?","Have you felt anxiety or worry that is difficult to control?","Have your feelings affected sleep or concentration?","Have you started avoiding things or places because of fear or stress?","Have these feelings affected study, work, or relationships?"][i])}</p><div class="assessment-options">${[0,1,2,3].map(v=>`<label><input type="radio" name="q${i}" value="${v}">${esc(state.lang==="ar"?["أبدًا","أحيانًا","غالبًا","تقريبًا يوميًا"][v]:["Never","Sometimes","Often","Nearly every day"][v])}</label>`).join("")}</div></div>`).join("")}
  function calculateAssessment(){let total=0,answered=0;questions.forEach((_,i)=>{const v=$("input[name=q"+i+"]:checked");if(v){total+=Number(v.value);answered++}});const result=$("#assessmentResult");if(answered<questions.length){result.textContent=t("أجب عن الأسئلة الخمسة أولًا حتى تكون النتيجة الإرشادية أكمل.","Answer all five questions first for a more complete reflection.");result.classList.add("show");return}let msg;if(total<=4)msg=t("الإجابات لا تشير إلى مستوى مرتفع من الضيق في هذا التقييم القصير. استمر في ملاحظة حالتك، وإذا تغيرت بشكل واضح تحدث مع مختص.","Your answers do not suggest a high level of distress in this brief reflection. Keep noticing how you feel, and seek professional support if things change significantly.");else if(total<=9)msg=t("توجد بعض مؤشرات الضيق في إجاباتك. قد يكون من المفيد قراءة الموضوعات المناسبة والتحدث مع شخص موثوق أو مختص إذا استمرت الأعراض.","Your answers show some signs of distress. It may be useful to explore relevant topics and talk with someone you trust or a professional if symptoms persist.");else msg=t("تظهر في إجاباتك مؤشرات تستحق مزيدًا من الانتباه. فكّر في التحدث مع مختص مؤهل للحصول على تقييم مناسب، خصوصًا إذا كانت الأعراض تؤثر في حياتك اليومية.","Your answers show signs worth paying attention to. Consider speaking with a qualified professional for appropriate assessment, especially if symptoms affect daily life.");result.innerHTML=`<strong>${esc(t("نتيجة إرشادية فقط","Guidance only"))}</strong><p>${esc(msg)}</p><small>${esc(t("هذا ليس تشخيصًا ولا بديلًا عن التقييم المهني.","This is not a diagnosis and is not a substitute for professional evaluation."))}</small>`;result.classList.add("show")}
  function bind(){ $("#languageSwitch").addEventListener("click",()=>{state.lang=state.lang==="ar"?"en":"ar";localStorage.setItem("mindcare_language",state.lang);applyLanguage();if($("#assessmentModal").classList.contains("open"))renderAssessment()});$("#menuToggle").addEventListener("click",()=>$("#mainNav").classList.toggle("open"));document.addEventListener("click",e=>{const topic=e.target.closest("[data-topic]");if(topic){renderTopic(topic.dataset.topic);return}const prov=e.target.closest("[data-provider]");if(prov){renderProvider(prov.dataset.provider);return}const book=e.target.closest("[data-open-booking]");if(book){e.preventDefault();openBooking(book.dataset.selectedProvider||"");return}if(e.target.closest("[data-close-modal]")){closeModals();return}});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModals()});$("#bookingProvider").addEventListener("change",loadSlots);$("#bookingDate").addEventListener("change",loadSlots);$("#bookingForm").addEventListener("submit",submitBooking);$$('.faq-question').forEach(q=>q.addEventListener("click",()=>q.closest(".faq-item").classList.toggle("open")));$("#assessmentButton").addEventListener("click",()=>{renderAssessment();$("#assessmentResult").classList.remove("show");openModal("#assessmentModal")});$("#calculateAssessment").addEventListener("click",calculateAssessment);document.addEventListener("scroll",()=>{const y=scrollY+120;$$('.nav-link').forEach(a=>{const sec=$(a.getAttribute("href"));a.classList.toggle("active",!!sec&&y>=sec.offsetTop&&y<sec.offsetTop+sec.offsetHeight)});});$("#year").textContent=new Date().getFullYear()}
  initFirebase();bind();applyLanguage();loadCustomTopics();
})();
